spring.application.name=healthprovider-service

### Mongo DB Config
#spring.mongodb.uri=mongodb://root:rootpassword@localhost:27017/healthprovider-db?authSource=admin
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=healthprovider-db
spring.mongodb.username=root
spring.mongodb.password=rootpassword
spring.mongodb.authentication-database=admin

### Eureka Config
#Turn off Client if not run already
#eureka.client.enabled=false

eureka.client.service-url.defaultZone=http://localhost:9092/eureka/
eureka.instance.prefer-ip-address=true
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true

### 08-observability: Actuator properties
#management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0

### 09-elk:
# 'Custom' path to our local machine directory
app.logs.fileLocation=C:\\Users\\a5161787\\Downloads\\microservices-logs

### 10-grafana-stack: Actuator properties
management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=healthprovider-service

server.port=9091