CREATE DATABASE IF NOT EXISTS auth_service;
USE auth_service;

CREATE TABLE users_seq (
    next_val bigint
);

CREATE TABLE IF NOT EXISTS USERS
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100),
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(150),
    CONTACT INT,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_USERS_USERNAME (USERNAME),
    UNIQUE KEY UK_USERS_EMAIL (EMAIL)
);

CREATE TABLE IF NOT EXISTS ROLES
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_ROLES_NAME (`NAME`)
);

CREATE TABLE IF NOT EXISTS USERS_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLES_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLES_ID),
    CONSTRAINT FK_USER_ROLES_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_USER_ROLES_ROLE
        FOREIGN KEY (ROLES_ID) REFERENCES ROLES(ID)
);

INSERT INTO users_seq VALUES (1);
-- INSERT INTO ROLES(NAME) VALUES('ADMIN');
-- INSERT INTO ROLES(NAME) VALUES('USER');